export class Transcation {
        transactionId
        date
        buyerEmail 
        sellerEmail
        productSend
        productObtained
        method_of_Transaction 
        price_of_Product_in_coins
        historyDetails
        exchangeProductList
        image
        pcoin1
    pname1
    pcategory1
    pcoin2
    pname2
    pcategory2
    ename
    eemail
    image1
    image2
    userId;
	   rating=1;
	    reviews;
}
