##eureka:
##  client:
##    service-url:
##      defaultZone:
##    register-with-eureka:
##    fetch-registry:
#server:
#  port: 8080
#spring:
#  application:
#    name: "api-gateway"
#  cloud:
#    gateway:
#      globalcors:
#        corsConfigurations:
#          '[/**]':
#            allowedOrigins: '*'
#            allowedMethods: '*'
#            allowedHeaders: '*'
#            exposedHeaders: '*'
#      routes:
#        - id: authentication-service
#          uri: http://localhost:8081/
#          predicates:
#            - Path=/authenticationservice/**
#          filters:
#            - RewritePath=/authenticationservice(?<segment>/?.*), $\{segment}
#        - id: chat-service
#          uri: http://localhost:9090/
#          predicates:
#            - Path=/chatservice/**
#          filters:
#            - RewritePath=/chatservice(?<segment>/?.*), $\{segment}
#        - id: recommendation-service
#          uri: http://localhost:8090/
#          predicates:
#            - Path=/recommendationservice/**
#          filters:
#            - RewritePath=/recommendationservice(?<segment>/?.*), $\{segment}
#        - id: email
#          uri: http://localhost:9292/
#          predicates:
#            - Path=/emailservice/**
#          filters:
#            - RewritePath=/emailservice(?<segment>/?.*), $\{segment}
#        - id: product-service
#          uri: http://localhost:8083/
#          predicates:
#            - Path=/productservice/**
#          filters:
#            - RewritePath=/productservice(?<segment>/?.*), $\{segment}
#        - id: Transaction_History
#          uri: http://localhost:8078/
#          predicates:
#            - Path=/transactionservice/**
#          filters:
#            - RewritePath=/transactionservice(?<segment>/?.*), $\{segment}
#        - id: user-service
#          uri: http://localhost:9998/
#          predicates:
#            - Path=/userservice/**
#          filters:
#            - RewritePath=/userservice(?<segment>/?.*), $\{segment}